# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Custom vars
version:          1.0.1


# Setup
title:             Lab Notebook
tagline:          'Michelle Evans'
description:      'One time Tad taught me how to make a lab notebook...'
baseurl:          /sampleNotebook

paginate:         5

github:
  repo:           https://github.com/mvevans89/sampleNotebook
