

# Setup
title:             Lab Notebook
tagline:          'Michelle Evans'
description:      ''
baseurl:          /LabNotebook

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/mvevans89/LabNotebook
