# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:             Lab Notebook
tagline:          'Tad Dallas'
description:      'Incorporating natural science and the science of man'
baseurl:          /LabNotebook

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/taddallas/LabNotebook
